### ISSUE TITLE
Substitute a standard phrase for the post content when post is gutted

### ISSUE THREAD

**Issue by idreyn** [LLK/s2forums#1164]
Problem:  Some users have edited posts and removed all the content.  Then, they have used the Report feature to ask to have the post deleted by a moderator.  However, with no content in the post, the link to the post is missing in the report queue and the moderator has a difficult time locating the post. 

Solution:  When building an entry in the report queue, check to see if the post is empty.  If it is empty, substitute the word "(empty post)" as the link text in the report queue.  Alternatively, if it's cleaner, we could actually force the contents of the post to be non-empty and actually stick "(empty post)" in the post.
__Reporter:__ Mark Goff
__Begin:__ 2013-07-24
__Completed:__ 0

**Comment by Harakou** [comment]
Bump. Working on this issue because it can be a bit of a nuisance. Would we rather prevent users from blankposting entirely, or just update the report model so that if it is blank, there's stand-in text in the report?
