### ISSUE TITLE
Parse Post and Title Text with Cleanspeak

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1294]
We should use the Cleanspeak text filter to check for inappropriate language in topic titles and posts.  We will need to figure out if we want tickets to be generated or just replace the text with asterisks, as we do now, or block the text from being entered at all.

It probably makes the most sense to copy the logic that we use in comments as far as possible, with severe language being blocked completely while more mild offenses get silently ticketed - only the tickets would be generated on the forum reports queue rather than the regular ticket queue.

**Comment by an-OK-squirrel** [comment]
Why would you want to do this? Your regexp seems to work better than Cleanspeak most of the time.
