### ISSUE TITLE
Ban Spammer function not working for Forum Moderator

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1314]
It's working for Scratch Team members - but not for sparks, one of our last Scratchers from the "Forum Moderator" group.

http://scratch.mit.edu/nothingtoseehere/auth/user/183006/

he says it used to work - but as of the last deploy, it does not

"@Paddle - this was the report button under the user's thumbnail in the forum post. Clicking it just takes me to the scratch homepage after giving me a warning message asking if I'm sure"

It should take him to the spammers profile rather than the Scratch homepage.  And it should block the spammer's account.  He reports no JS errors in the console.  

sparks is one of our frontline anti-spam defenders.  Since he's in the UK, he is 5 hours ahead of us - he's covering hours that nobody else is.  It would be very helpful if he got this functionality back soon.

**Comment by kaschm** [comment]
@paddle2see - is this still an issue? just stumbled across this one - sorry for the lapse!

**Comment by Paddle2See** [comment]
@kaschm Yes, this is still a problem.

**Comment by mewtaylor** [comment]
Test Case:

As a user who is a Forum Moderator (i.e. is in that admin group) but not a superuser (i.e. not a moderator), try to ban a spammer by clicking on the link "Ban User & Delete All Posts" on a user's forum post. You should be redirected to that user's page, and they should be banned.

**Comment by 2jour** [comment]
@Paddle2See verified :)
