### ISSUE TITLE
Paste OS/Browser/Flash versions not working on Edits

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1315]
The little globe button that inserts the OS/Brower/Flash versions into forum posts works fine when a post is created, giving a format like this:

My browser / operating system: Windows 7, Chrome 36.0.1985.143, Flash 14.0 (release 0)

however, if you try to insert the information on an edited post, all you get is the last part:

, Flash 14.0 (release 0)

Also, when you are editing your signature, the button is available - but, again, all you get is the last portion of the information string:

, Flash 14.0 (release 0)

The signature issue is not high priority - but the ability to add it to an edited post is pretty important since a lot of users (including me) have realized after they hit the "Submit" button that they should have included that - so they go to edit the post and - it doesn't work.  If we want better bug reports from our users, we need to give them the tools to do it.

Sample forum topic used to play around with the issue is here

http://scratch.mit.edu/discuss/topic/49465/

Forum post about the issue is here

http://scratch.mit.edu/discuss/topic/41074/

**Comment by 2jour** [comment]
Tested today and this scenario does not work

After forum post Submit,  click edit on post and click globe to add info of OS/browser info using globe. 

I get only the flash version

It was working, Feb 25

**Comment by 2jour** [comment]
LGTM
