### ISSUE TITLE
Text entered in a post enclosed in square brackets becomes invisible

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1316]
If you enter text like enclosed in square brackets like this:

              You are a [completely idiotic] person whom I [do not] admire.

It will display as 

              You are a person whom I admire.

but when you quote it, the original bracket enclosed text reappears.  

Naturally, the kids are having a ball with this and it is making moderation more difficult.  With text set to the background color (another way to make invisible text), you can at least see it by selecting it.  That doesn't work with the bracket enclosed text - the only way to see it is to edit or quote the post - rather tedious.

**Comment by MegaApuTurkUltra** [comment]
This is the way bbcode tags are supposed to work. Maybe the bbcode should be verified for syntax before posting, and it shouldn't let you post with invalid bbcode. This would also prevent another major problem, people not closing their scratchblocks or quote tags and screwing quoters' posts up.

The verification should give helpful messages and try to guess where the fix should go. Something like
> Uh oh! It looks like you didn't add a [/scratchblocks] tag to go with your [scratchblocks] one! [Add it for me](#)

or
> Uh oh! It seems you have a [completely idiotic] tag, which our servers don't recognize! [Remove it for me](#)
