### ISSUE TITLE
Forum Signature not filtered for obscenity

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1317]
It would seem that we are not filtering text entered into the forum signature area.  This leaves us somewhat vulnerable to a troll attack since we allow New Scratchers to have a forum signature.  See example here:

http://jiggler.media.mit.edu/discuss/post/270404/

**Comment by mewtaylor** [comment]
@Paddle2See just so I'm clear - filter for spam (i.e. akismet), or filter for language (i.e. cleanspeak)?

**Comment by Paddle2See** [comment]
@mewtaylor Filter for language.  However, Cleanspeak has never been set up in the forums and I'm not sure if we want to take on integrating it into the ticket system right now.  I was hoping you could just run the simple Regex substitution that we use on forum posts to get rid of the worst of the ugly language.

**Comment by mewtaylor** [comment]
Yup sounds good thanks!

**Comment by mewtaylor** [comment]
Test Case: post bad language (i.e. language that could be found in this regex: https://github.com/LLK/s2forums/blob/master/djangobb_forum/scratchr2_settings.py#L36) in the signature of a user, and make sure it gets filtered out and replaced with a star.

**Comment by mewtaylor** [comment]
@2jour just making sure you're aware there's a needs-qa tag in the forums - I know we don't always have stuff here :)
