### ISSUE TITLE
New Scratchers are editing their posts using the URL

### ISSUE THREAD

**Issue by Paddle2See** [LLK/s2forums#1328]
We don't want New Scratchers to be able to edit their posts as they can use it to troll and confuse the community.  That's why we don't give them an Edit button on their posts.  

Unfortunately, it turns out that as a New Scratcher, you can still edit your own posts if you put in the URL directly into your browser:

scratch.mit.edu/discuss/post/xxxx/edit

where xxxx is the post number.

Can we find a way to make that stop working - by testing permissions perhaps?

**Comment by kingofepicness** [comment]
Change all of the scratch.mit.edu/discuss/post/xxxx/edit to hard to remember links like scratch.mit.edu/editpost-xxxxxxxxxxxxxxxxxxxxxxx or maybe that would be hard. I am new to coding but maybe that would work.

**Comment by MegaApuTurkUltra** [comment]
Noooo, please don't fix this!

Also @kingofepicness I like to type edit URLs manually, and as I am a Scratcher, I would appreciate if that continued to work.

**Comment by kingofepicness** [comment]
In reply to @MegaApuTurkUltra Maybe new scratchers could have hard to remember URLs and scratchers don't?

**Comment by MegaApuTurkUltra** [comment]
@kingofepicness it's not about how easy it is to remember. The process of typing a URL manually goes something like:

1. Find the date at the top left of your post, right click > copy url
2. Paste URL into url bar
3. Add `/edit` after the url you pasted
4. Hit enter

It wouldn't be easy to change the forums to have every post have a giant ID number, nor would it help prevent people from using the edit link.

**Comment by kingofepicness** [comment]
@MegaApuTurkUltra Oh sorry about that. I am still quite new to GitHub coding. Perhaps the New scratchers could have dates hidden?

**Comment by MegaApuTurkUltra** [comment]
@kingofepicness yes, but there are other ways of finding your post ID (from inspect element especially) so what the ST was saying here is to just have the server refuse to serve the edit page if it detects that the current user is a new scratcher.

**Comment by Harakou** [comment]
@MegaApuTurkUltra Essentially, this is correct. The forum software naturally knows all about who is logged in, so it's much easier and better for UX to just check if the person logged in has the right permissions to edit. You can see that we have this sort of check already in place for other functions, like [here.](https://github.com/LLK/s2forums/blob/master/djangobb_forum/views.py#L1048) :)
