### ISSUE TITLE
Obfuscate swear filter

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/s2forums#1335]
It doesn't look good as it is, and it prevents anyone from being able to link to basically anything on this repo from Scratch. Even a simple [rot13 encode](https://github.com/OpenSprites/OpenSprites/blob/master/public_html/assets/includes/validate.php#L4) (looks like gibberish) would work. Anyone who knows how to run the code to decode it should be fine with the swears / knows they're doing it at their own risk.

**Comment by an-OK-squirrel** [comment]
I agree with this.

but at least it has regexps in some parts.

**Comment by dwminer** [comment]
3e6e5d45450699cd04bcd2bcb20f9aeaab413da1

**Comment by an-OK-squirrel** [comment]
Sweet.
