### ISSUE TITLE
Auto Ban if a post receives enough reports

### ISSUE THREAD

**Issue by idreyn** [LLK/s2forums#251]
This feature provides automatic protection from spammers and trolls that might be posting when moderators are not present.  Here's how it works:

1. Maintain a score for each post (integer)

2. The score starts as zero when the post is created and is incremented by one if a post is Reported by a full Scratcher that has not already placed a report on the post.  Reports by CM or ST members do not change the score. 

3. If the post is by a CM or ST member, the score is not incremented

4. If the score reaches a trigger level (adjustable - set to 4), the post content is removed from view and replaced with a "being reviewed" message in a contrasting color (currently red).  The owner of the post is blocked and IP blocked for a temporary period (one day) with a block message indicating that their posts are being reviewed.  Check to see if the owner of the post is already blocked - do not block more than once.

5. When any reports of the post are zapped, the score is reset to zero and the regular post content is restored.  The blocks are not removed.

6. The text of the Report that triggered the block is amended to include the words "Autoban Invoked" to let the CM or ST member know that a block was placed that needs review.
__Reporter:__ Mark Goff
__Assigned to:__ Nathan Dinsmore
__Begin:__ 2012-12-18
__Completed:__ 0

**Comment by kaschm** [comment]
@speakkvisually is this still a relevant issue or should we close it?

**Comment by kaschm** [comment]
@speakkvisually ping!
